env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:svelte/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  extraFileExtensions: ['.svelte']
plugins:
  - "@typescript-eslint"
overrides:
  - files: ["*.svelte"]
    parser: svelte-eslint-parser
    parserOptions:
        parser: "@typescript-eslint/parser"
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      functions: only-multiline
  indent:
    - error
    - tab
  quotes:
    - warn
    - double
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/ban-ts-comment": off
