# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout to head
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Install dependencies
      run: make node_modules

    - name: Copy config file
      run: make config.json

    - name: Build
      run: make

  #   - name: Run tests
  #     run: npm test

  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to head
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Install Apt dependencies
      run: sudo apt-get install -y jq

    - name: Install Node dependencies
      run: make node_modules

    - name: Run checks
      run: |
        echo "::add-matcher::.github/matchers/svelte-check.json"
        make check -k
        echo "::remove-matcher owner=svelte-check::"
